from __future__ import annotations

from enum import Enum


class RejectionStage(str, Enum):
    THESIS = "THESIS"
    INTENT = "INTENT"
    BINDING = "BINDING"
    PRICING = "PRICING"
    RISK = "RISK"
    PUBLICATION = "PUBLICATION"


class RejectionCode(str, Enum):
    NO_THESIS = "NO_THESIS"
    THESIS_TOO_WEAK = "THESIS_TOO_WEAK"

    NO_MARKET_INTENT = "NO_MARKET_INTENT"
    FAMILY_DISABLED = "FAMILY_DISABLED"

    OFFER_NOT_FOUND = "OFFER_NOT_FOUND"
    EVENT_ID_MISMATCH = "EVENT_ID_MISMATCH"
    TEMPLATE_BIND_FAILED = "TEMPLATE_BIND_FAILED"
    MARKET_UNAVAILABLE = "MARKET_UNAVAILABLE"

    PRICE_TOO_LOW = "PRICE_TOO_LOW"
    PRICE_TOO_HIGH = "PRICE_TOO_HIGH"
    PRICE_STALE = "PRICE_STALE"
    IMPLIED_PROBABILITY_INVALID = "IMPLIED_PROBABILITY_INVALID"
    EDGE_TOO_LOW = "EDGE_TOO_LOW"
    EV_TOO_LOW = "EV_TOO_LOW"

    RISK_BLOCKED = "RISK_BLOCKED"
    DUPLICATE_THESIS = "DUPLICATE_THESIS"

    PUBLICATION_POLICY = "PUBLICATION_POLICY"
    UNKNOWN = "UNKNOWN"